import importlib.metadata
from pathlib import Path
import subprocess


def read_pyproject_version():
    try:
        import tomllib
        pyproject = Path(__file__).with_name("pyproject.toml")
        if pyproject.exists():
            with pyproject.open("rb") as f:
                data = tomllib.load(f)
            return data.get("project", {}).get("version")
    except Exception:
        return None


def get_version() -> str:
    # 1. Try metadata (installed package)
    try:
        return importlib.metadata.version("luban-hello-world-py")
    except importlib.metadata.PackageNotFoundError:
        pass

    # 2. Try baked-in version file (generated by hatch-vcs)
    try:
        from _version import __version__
        return __version__
    except ImportError:
        pass

    # 3. Try git (development environment)
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--dirty", "--always"],
            cwd=Path(__file__).parent,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=False,
        )
        v = result.stdout.strip()
        if v:
            return v
    except Exception:
        pass

    # 4. Try pyproject.toml (static version fallback)
    pv = read_pyproject_version()
    if pv:
        return pv

    return "0.0.0"


__version__ = get_version()
